In [9]:
import os
import tqdm
import wandb
import warnings
import numpy as np
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import concurrent.futures

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # Suppress TensorFlow logging
warnings.filterwarnings('ignore', category=UserWarning, module='google.protobuf')

from matplotlib.axes import Axes
from wandb.apis.public import Run

from typing import Union, List, Dict
from src.visualization import set_themes
from IPython.display import Markdown

set_themes() # Set custom themes for plots
pl.Config.set_tbl_rows(20) # Set Polars table display rows limit

pd.set_option('future.no_silent_downcasting', True)

In [10]:
cache_file = "wandb/summary.parquet"
config = {
    "model": "matrix_factorization",
    "ensure_available_locally": False
}
sorting_criterion = {
    "epoch/test_hitrate@50": 0.5,
    "epoch/test_ndcg@50": 0.25,
}

if cache_file is not None and os.path.exists(cache_file):
    print(f"Loading cached experiment runs from {cache_file}...")
    experiment_runs = pl.read_parquet(cache_file)
    print(f"Loaded {len(experiment_runs)} runs from cache.")
else:
    print("No cache file found. Fetching experiment runs from Weights & Biases...")
    api = wandb.Api() # Initialize Weights & Biases API, used for fetching run data

    def fetch_run_metadata(run: Run, considered_metrics: Union[str, Dict[str, float]] = "epoch/epoch") -> Dict:
        run_config = {}
        for key, value in run.config.items():
            # Convert lists and dicts to strings
            if isinstance(value, (list, dict)):
                run_config[key] = str(value)
            else:
                run_config[key] = value

        run_history = run.history()
        run_history = run_history.replace({"Infinity": np.inf, "NaN": np.nan})

        if isinstance(considered_metrics, str):
            run_history["score"] = run_history[considered_metrics]
        elif isinstance(considered_metrics, dict):
            run_history["score"] = sum(
                run_history[metric] * weight for metric, weight in considered_metrics.items()
            )
        else:
            raise ValueError("considered_metrics must be either a string or a dictionary")
        
        best_summary = run_history.iloc[run_history["score"].argmax()]
        best_summary = {f"best:{key}": val for key, val in best_summary.items()}
        
        return {
            "run_id": run.id,
            "run_name": run.name,
            "sweep_id": run.sweep.id if run.sweep else None,
            "model": run.config.get("model"),
            **run_config,
            **{metric: run_history[metric].to_list() for metric in run_history},
            **best_summary,
            "gpu_type": run.metadata.get("gpu"),
            "cpu_count": run.metadata.get("cpu_count"),
        }

    batch_size = 16
    records = []
    futures = {}
    executor = concurrent.futures.ThreadPoolExecutor(max_workers=batch_size)
    runs:List[Run] = api.runs("feedr/peppermint-matrix", per_page=2*batch_size-1, filters={"config.model": config["model"]})
    run_iterator = iter(runs)
    with tqdm.tqdm(total=len(runs), ncols=128) as pbar:
        while len(records) < len(runs):
            # submit new tasks if we empty slots in the batch
            while len(futures) < batch_size and len(records) + len(futures) < len(runs):
                current_runs = next(run_iterator)
                current_future = executor.submit(fetch_run_metadata, current_runs, sorting_criterion)
                futures[current_future] = current_runs

            # check for completed tasks
            finished_futures, _ = concurrent.futures.wait(futures.keys(), return_when=concurrent.futures.FIRST_COMPLETED, timeout=0.1)
            for finished_future in finished_futures:
                finished_run = futures.pop(finished_future)
                records.append(finished_future.result())
                pbar.update(1)

    # Create a Polars DataFrame from the records
    experiment_runs = pl.DataFrame(records, infer_schema_length=None)
    
# Tag run as available locally if the model files exist
local_run_ids = []
local_sweep_ids = os.listdir(f"./models/{config['model']}/")
for sweep_id in local_sweep_ids:
    local_run_ids.extend([run_id for run_id in os.listdir(f"./models/{config['model']}/{sweep_id}/")])
    
experiment_runs = experiment_runs.with_columns(
    available_locally=pl.col("run_id").is_in(local_run_ids)
)

if config["ensure_available_locally"]:
    experiment_runs = experiment_runs.filter(pl.col("available_locally") == True)

experiment_runs = experiment_runs.sort("_timestamp", descending=False)
experiment_runs = experiment_runs.with_columns(
    run_duration_second=pl.col("_runtime").list.max(),
    run_duration_minute=(pl.col("_runtime").list.max() / 60)
)
experiment_runs.select(
    pl.col("run_id"),
    pl.col("run_name"),
    pl.col("sweep_id"),
    pl.col("model"),
    pl.col("embedding_dimension"),
    pl.col("shuffle"),
    pl.col("best:epoch/epoch"),
    pl.col("best:epoch/train_loss"),
    pl.col("best:epoch/test_loss"),
    pl.col("best:epoch/train_recall@10"),
    pl.col("best:epoch/train_ndcg@10"),
    pl.col("best:epoch/test_recall@10"),
    pl.col("best:epoch/test_ndcg@10"),
)

Loading cached experiment runs from wandb/summary.parquet...
Loaded 3382 runs from cache.

shape: (3_382, 13)
┌──────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ run_id   ┆ run_name   ┆ sweep_id ┆ model     ┆ … ┆ best:epoc ┆ best:epoc ┆ best:epoc ┆ best:epoc │
│ ---      ┆ ---        ┆ ---      ┆ ---       ┆   ┆ h/train_r ┆ h/train_n ┆ h/test_re ┆ h/test_nd │
│ str      ┆ str        ┆ str      ┆ str       ┆   ┆ ecall@10  ┆ dcg@10    ┆ call@10   ┆ cg@10     │
│          ┆            ┆          ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆            ┆          ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ o94q0juk ┆ logical-sw ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.035844  ┆ 0.359888  ┆ 0.026077  ┆ 0.100539  │
│          ┆ eep-1      ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 4ftaae0p ┆ stilted-sw ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.007561  ┆ 0.085169  ┆ 0.006594  ┆ 0.02556   │
│          ┆ eep-3      ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ fway5u2z ┆ breezy-swe ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.00596   ┆ 0.065856  ┆ 0.0026    ┆ 0.012059  │
│          ┆ ep-4       ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ bphcl2xf ┆ clean-swee ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.162349  ┆ 0.79712   ┆ 0.024744  ┆ 0.095121  │
│          ┆ p-2        ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ dcbj92eg ┆ ruby-sweep ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.091837  ┆ 0.637288  ┆ 0.024295  ┆ 0.094158  │
│          ┆ -8         ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ x17mnyw8 ┆ breezy-swe ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.034525  ┆ 0.346527  ┆ 0.023699  ┆ 0.089898  │
│          ┆ ep-9       ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 7jrm756b ┆ super-swee ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.003005  ┆ 0.043139  ┆ 0.002425  ┆ 0.010531  │
│          ┆ p-10       ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ lwy6xxpj ┆ gallant-sw ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.003378  ┆ 0.057032  ┆ 0.000982  ┆ 0.003957  │
│          ┆ eep-11     ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 08sbuv2x ┆ morning-sw ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.005272  ┆ 0.070258  ┆ 0.004887  ┆ 0.022104  │
│          ┆ eep-16     ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ icy1168r ┆ graceful-s ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.001701  ┆ 0.023641  ┆ 0.000734  ┆ 0.002861  │
│          ┆ weep-17    ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2izjuafo ┆ raspberry- ┆ null     ┆ matrix_fa ┆ … ┆ 0.000263  ┆ 0.004428  ┆ 0.000315  ┆ 0.001409  │
│          ┆ mousse-604 ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆ 5          ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ jq3jh95y ┆ cookies-n- ┆ null     ┆ matrix_fa ┆ … ┆ 0.000278  ┆ 0.00472   ┆ 0.000277  ┆ 0.00132   │
│          ┆ cream-squa ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆ re-6046    ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ wqaviq6b ┆ pecan-mous ┆ null     ┆ matrix_fa ┆ … ┆ 0.000292  ┆ 0.005204  ┆ 0.000337  ┆ 0.00157   │
│          ┆ se-6047    ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ wyzkc01l ┆ maple-crum ┆ null     ┆ matrix_fa ┆ … ┆ 0.046594  ┆ 0.423237  ┆ 0.024905  ┆ 0.098609  │
│          ┆ ble-6048   ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ j4zcv4wb ┆ butterscot ┆ null     ┆ matrix_fa ┆ … ┆ 0.070072  ┆ 0.534029  ┆ 0.024187  ┆ 0.096318  │
│          ┆ ch-bun-604 ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆ 9          ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ lpx3gfas ┆ cookies-n- ┆ null     ┆ matrix_fa ┆ … ┆ 0.127214  ┆ 0.718716  ┆ 0.024005  ┆ 0.094259  │
│          ┆ cream-past ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆ ry-6050    ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 2yqggl19 ┆ pumpkin-pa ┆ null     ┆ matrix_fa ┆ … ┆ 0.197194  ┆ 0.873555  ┆ 0.022788  ┆ 0.089314  │
│          ┆ stry-6051  ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 7rhnlp8q ┆ berry-bun- ┆ null     ┆ matrix_fa ┆ … ┆ 0.045351  ┆ 0.416218  ┆ 0.025054  ┆ 0.097724  │
│          ┆ 6052       ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ wvjmx8hy ┆ cherry-fla ┆ null     ┆ matrix_fa ┆ … ┆ 0.069224  ┆ 0.531303  ┆ 0.02506   ┆ 0.096649  │
│          ┆ n-6053     ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ wjozqf9f ┆ turtle-fla ┆ null     ┆ matrix_fa ┆ … ┆ 0.122758  ┆ 0.711726  ┆ 0.023814  ┆ 0.094419  │
│          ┆ n-6054     ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
└──────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# 28-01-2026 Adding Dropout
We need to make sure adding Dropout layer dont actually change the model in a negative way if dropout rate is set to 0.

In [15]:
experiment_runs_testcase1 = experiment_runs.filter(
    pl.col("shuffle") == False,
    pl.col("embedding_dimension") == 128,
    pl.col("l2_regularization") == 1e-7,
    pl.col("l1_regularization") == 0.0,
    pl.col("embedding_dropout_rate") == 0.0
)
experiment_runs_testcase1 = experiment_runs_testcase1.with_columns(
    test_group = pl.when(pl.col("created_at").dt.truncate("1d") <= pl.datetime(2026, 1, 27)).then(pl.lit("A")).otherwise(pl.lit("B")),
)
experiment_runs_testcase1

shape: (13, 144)
┌──────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ run_id   ┆ run_name   ┆ sweep_id ┆ model     ┆ … ┆ available ┆ run_durat ┆ run_durat ┆ test_grou │
│ ---      ┆ ---        ┆ ---      ┆ ---       ┆   ┆ _locally  ┆ ion_secon ┆ ion_minut ┆ p         │
│ str      ┆ str        ┆ str      ┆ str       ┆   ┆ ---       ┆ d         ┆ e         ┆ ---       │
│          ┆            ┆          ┆           ┆   ┆ bool      ┆ ---       ┆ ---       ┆ str       │
│          ┆            ┆          ┆           ┆   ┆           ┆ f64       ┆ f64       ┆           │
╞══════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 4v2l14ai ┆ clear-swee ┆ nbysw136 ┆ matrix_fa ┆ … ┆ false     ┆ 645.65009 ┆ 10.760835 ┆ A         │
│          ┆ p-44       ┆          ┆ ctorizati ┆   ┆           ┆ 7         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 33f22vxh ┆ peachy-swe ┆ nbysw136 ┆ matrix_fa ┆ … ┆ false     ┆ 639.38463 ┆ 10.656411 ┆ A         │
│          ┆ ep-70      ┆          ┆ ctorizati ┆   ┆           ┆ 1         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ a6daodlj ┆ splendid-s ┆ nbysw136 ┆ matrix_fa ┆ … ┆ false     ┆ 728.04182 ┆ 12.13403  ┆ A         │
│          ┆ weep-79    ┆          ┆ ctorizati ┆   ┆           ┆ 1         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ b46nfk8u ┆ lunar-swee ┆ nbysw136 ┆ matrix_fa ┆ … ┆ false     ┆ 672.15251 ┆ 11.202542 ┆ A         │
│          ┆ p-80       ┆          ┆ ctorizati ┆   ┆           ┆ 1         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ ivpuqxwp ┆ sweet-swee ┆ ryvorbif ┆ matrix_fa ┆ … ┆ false     ┆ 704.41976 ┆ 11.740329 ┆ A         │
│          ┆ p-314      ┆          ┆ ctorizati ┆   ┆           ┆ 3         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ ih67q1sh ┆ bumbling-s ┆ ryvorbif ┆ matrix_fa ┆ … ┆ false     ┆ 648.07217 ┆ 10.801203 ┆ A         │
│          ┆ weep-433   ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ fddyc517 ┆ crisp-swee ┆ ryvorbif ┆ matrix_fa ┆ … ┆ false     ┆ 735.93223 ┆ 12.265537 ┆ A         │
│          ┆ p-451      ┆          ┆ ctorizati ┆   ┆           ┆ 7         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ olyu0hd6 ┆ lively-swe ┆ jj74ffn0 ┆ matrix_fa ┆ … ┆ false     ┆ 678.31592 ┆ 11.305265 ┆ B         │
│          ┆ ep-57      ┆          ┆ ctorizati ┆   ┆           ┆ 3         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ qa43zu9j ┆ legendary- ┆ jj74ffn0 ┆ matrix_fa ┆ … ┆ false     ┆ 665.25954 ┆ 11.087659 ┆ B         │
│          ┆ sweep-263  ┆          ┆ ctorizati ┆   ┆           ┆ 2         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 2w2pgtp6 ┆ playful-sw ┆ jj74ffn0 ┆ matrix_fa ┆ … ┆ false     ┆ 691.87726 ┆ 11.531288 ┆ B         │
│          ┆ eep-301    ┆          ┆ ctorizati ┆   ┆           ┆ 3         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ msf3xs81 ┆ silvery-sw ┆ jj74ffn0 ┆ matrix_fa ┆ … ┆ false     ┆ 713.97989 ┆ 11.899665 ┆ B         │
│          ┆ eep-332    ┆          ┆ ctorizati ┆   ┆           ┆ 3         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ i9z1x5xu ┆ astral-swe ┆ jj74ffn0 ┆ matrix_fa ┆ … ┆ false     ┆ 686.78211 ┆ 11.446369 ┆ B         │
│          ┆ ep-372     ┆          ┆ ctorizati ┆   ┆           ┆ 1         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ stf85kgr ┆ leafy-swee ┆ jj74ffn0 ┆ matrix_fa ┆ … ┆ false     ┆ 679.69110 ┆ 11.328185 ┆ B         │
│          ┆ p-373      ┆          ┆ ctorizati ┆   ┆           ┆ 7         ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
└──────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [16]:
experiment_runs_testcase1.group_by("test_group").agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).to_pandas().transpose()

                                   0          1
test_group                         B          A
num_runs                           6          7
best:epoch/epoch           55.333333  55.714286
best:epoch/test_recall@10   0.028092   0.028188
best:epoch/test_ndcg@10     0.106602   0.106893
best:epoch/test_recall@20   0.048636   0.048909
best:epoch/test_ndcg@20     0.134482   0.134724